// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQCMO2MVNn-6H1ZYG6kzwUpsLxe0N79xs',
    appId: '1:754049704230:web:cee5da174efa6db78461e7',
    messagingSenderId: '754049704230',
    projectId: 'commune-mvp',
    authDomain: 'commune-mvp.firebaseapp.com',
    storageBucket: 'commune-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Wamg25CJ_j6xQlyAU_WRJiQGoXMEOpw',
    appId: '1:754049704230:android:97561c984be955408461e7',
    messagingSenderId: '754049704230',
    projectId: 'commune-mvp',
    storageBucket: 'commune-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC8ZG7q3xLhsjd7Nbr2VGfWozHfSfCYyo',
    appId: '1:754049704230:ios:d424c9f436ec8d988461e7',
    messagingSenderId: '754049704230',
    projectId: 'commune-mvp',
    storageBucket: 'commune-mvp.firebasestorage.app',
    iosBundleId: 'com.example.communeMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC8ZG7q3xLhsjd7Nbr2VGfWozHfSfCYyo',
    appId: '1:754049704230:ios:d424c9f436ec8d988461e7',
    messagingSenderId: '754049704230',
    projectId: 'commune-mvp',
    storageBucket: 'commune-mvp.firebasestorage.app',
    iosBundleId: 'com.example.communeMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQCMO2MVNn-6H1ZYG6kzwUpsLxe0N79xs',
    appId: '1:754049704230:web:14e1834301d012c28461e7',
    messagingSenderId: '754049704230',
    projectId: 'commune-mvp',
    authDomain: 'commune-mvp.firebaseapp.com',
    storageBucket: 'commune-mvp.firebasestorage.app',
  );

}